export const STEPPER = {
  STAGE_I_FORM: {
    PENDING: "STAGE_I__FEE_PENDING",
    PAID: "STAGE_I__FEE_PAID",
    EXEMPTED: "STAGE_I__FEE_EXEMPTED"
  },
  STAGE_II: {
    PENDING: "STAGE_II__FEE_PENDING",
    PAID: "STAGE_II__FEE_PAID",
    EXEMPTED: "STAGE_II__FEE_EXEMPTED"
  }
};