export const MENUITEMS = [
  {
    allowTo: ["applicant", "test"],
    menutitle: "DASHBOARD",
    menuGroup: "dashboard",
  },
  {

    allowTo: ["applicant", "test"],
    path: `${import.meta.env.BASE_URL}dashboard`,
    title: "Dashboard",
    icon: "ti-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    menuGroup: "dashboard",
  },
  {
    allowTo: ["applicant", "test"],
    menutitle: "NEW REGISTRATION",
    menuGroup: "new_registration",
  },
  {
    allowTo: ["applicant", "test"],
    path: `${import.meta.env.BASE_URL}dashboard/Application`,
    title: "Application",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    menuGroup: "new_registration",
  },
  {
    allowTo: ["test"],
    path: `${import.meta.env.BASE_URL}dashboard/new_registration`,
    title: "New Application",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    allowTo: ["test"],
    path: `${import.meta.env.BASE_URL}dashboard/form_stageII`,
    title: "stage II Form",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },

  //   {
  //     allowTo: "applicant",
  //     menutitle: "Example",
  //   },
  {
    allowTo: ["test"],
    path: `${import.meta.env.BASE_URL}dashboard/geoTaggedSample`,
    title: "Geo Tagged Sample",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    allowTo: ["state_assessor", "test"],
    menutitle: "Assessment",
  },
  {
    allowTo: ["state_assessor", "test"],
    path: `${import.meta.env.BASE_URL}dashboard/Assessment`,
    title: "Assessment",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    allowTo: ["state_assessor", "test"],
    path: `${import.meta.env.BASE_URL}dashboard/AssessmentII`,
    title: "AssessmentII",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    allowTo: ["test"],
    path: `${import.meta.env.BASE_URL}dashboard/TimeLine`,
    title: "TimeLine",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },
  {
    allowTo: ["test"],
    path: `${import.meta.env.BASE_URL}dashboard/TimeLine`,
    title: "TimeLine",
    icon: "ti-file",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
  },


  // RDSDE
  {
    allowTo: ["rdsde"],
    menutitle: "DASHBOARD",
    menuGroup: "dashboard",
  },
  {
    allowTo: ["rdsde"],
    path: `${import.meta.env.BASE_URL}dashboard/rdsde`,
    title: "Dashboard",
    icon: "ti-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    menuGroup: "dashboard",
  },
  {
    allowTo: ["rdsde"],
    path: `${import.meta.env.BASE_URL}dashboard/rdsde/compliances`,
    title: "Compliances",
    icon: "ti-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    menuGroup: "dashboard",
  },

  {
    allowTo: ["rdsde"],
		title: "Members", 
    icon: 'ti-wallet', 
    type: "sub", 
    active: false, 
    selected: false, 
    dirchange: false,
		
    children: [
			{ path: `${import.meta.env.BASE_URL}dashboard/rdsde/AddIcvcMember`, type: "link", active: false, selected: false, dirchange: false, title: "Add ICVC Member" },
      { path: `${import.meta.env.BASE_URL}dashboard/rdsde/MemberList`, type: "link", active: false, selected: false, dirchange: false, title: "Member List" },
      
		],
	},


  //STATE ADMIN
  {
    allowTo: ["state_admin"],
    menutitle: "DASHBOARD",
    menuGroup: "dashboard",
  },
  {
    allowTo: ["state_admin"],
    path: `${import.meta.env.BASE_URL}dashboard/state_admin`,
    title: "Dashboard",
    icon: "ti-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    menuGroup: "dashboard",
  },

  {
    allowTo: ["state_admin"],
		title: "Members", 
    icon: 'ti-wallet', 
    type: "sub", 
    active: false, 
    selected: false, 
    dirchange: false,
    children: [
			{ path: `${import.meta.env.BASE_URL}dashboard/state_admin/AddStateMembers`, type: "link", active: false, selected: false, dirchange: false, title: "Add State Members" },
		],
	},
];
